name: Terraform

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Terraform apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
